apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
        - name: backend1
          image: jhinga/blog-app-backend1:v0.0.3
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend1-config
            - secretRef:
                name: backend-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
        - name: backend2
          image: jhinga/blog-app-backend2:v0.0.3
          ports:
            - containerPort: 3001
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend2-config
            - secretRef:
                name: backend-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jhinga/blog-app-frontend:v0.0.3
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: frontend-config
