apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-ebs-claim
namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: auto-ebs-sc
  resources:
    requests:
      storage: 8Gi
