apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
stringData:
  POSTGRES_USER: krishna
  POSTGRES_PASSWORD: "hellosaurav"
  POSTGRES_DB: fellowship

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: dev
type: Opaque
stringData:
  CLERK_PUBLISHABLE_KEY: pk_test_cmVndWxhci1zYXR5ci0zMS5jbGVyay5hY2NvdW50cy5kZXYk
  CLERK_SECRET_KEY: sk_test_tFTEZn6QogIWeBc8XBLVt4juxAIEXzz2Coyg9Dc6Mv
  DB_HOST: postgres
  DB_USER: krishna
  DB_PASSWORD: hellosaurav
  DB_NAME: fellowship
